### ISSUE TITLE
Not playing nice with ivec2s in bevy 0.8

### ISSUE THREAD

**Issue by Cassumbra** [sarkahn/adam_fov_rs#1]
Updating my project to use bevy 0.8.
Suddenly, this crate gets mad at me when I use bevy's ivec2s?
Using ivec2s from glam does not seem to placate the crate either.
Not sure if this is simply an issue on my side, or something to do with bevy, or something to do with this crate.

**Comment by sarkahn** [comment]
Sounds like a version mismatch/conflicting dependency somewhere, what version of this crate are you using? What are your other dependencies?

**Comment by sarkahn** [comment]
Realized I had updated this for bevy 0.8 but never pushed the changes, so the crates version was using an older version of glam which probably would cause the issues you described. Can you try updating adam_fov_rs to 0.2 and see if it's fixed?
